substitutions:
  # Change this to your device name
  device_name: my-heating-control
  friendly_name: My Heating Control

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  # ... (other standard ESPHome settings like platform, board, etc.)

external_components:
  - source:
      # This component is loaded directly from GitHub.
      github://Deafoult/esphome-valve-sequencer@main

esp32:
  board: esp32dev
  # ...
logger:
api:
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light # Enables Wi-Fi power saving mode

# 1. Define the outputs for your relays
output:
  - platform: gpio
    id: relay_kitchen
    pin: 4
  - platform: gpio
    id: relay_living_room
    pin: 16
    inverted: true # Example for a relay that switches on LOW


valve_sequencer:
  max_concurrent: 5
  open_time: 5min
  global_status_sensor:
    name: "Heating System Status"
    id: heating_system_status
  # 2. Configure the heating circuits and reference the outputs defined above.
  circuits:
    - name: "Kitchen Heating Circuit"
      id: kitchen_heating_circuit
      output: relay_kitchen
    - name: "Living Room Heating Circuit"
      id: living_room_heating_circuit
      output: relay_living_room
      inverted: true # Example: This relay is Active-Low.
    - name: "Bathroom Heating Circuit"
      id: bathroom_heating_circuit
      output: relay_bathroom
      inverted: true # This valve is controlled with inverted logic, even though the 'relay_bathroom' output is not defined as inverted.
    # --- Add your other heating circuits here ---
    # - name: "My Other Circuit"
    #   output: my_other_relay_id